[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "matgraphdb"
authors = [
    {name = "Logan Lang", email = "lllang@mix.wvu.edu"}
]
description = "Welcome to MatGraphDB, a powerful Python package designed to interface with primary and graph databases for advanced material analysis."
readme = {file = "README.md", content-type = "text/markdown"}  # Ensure this matches the file used
requires-python = ">=3.8"
keywords = ["materials", "science", "graph", "database", "python"]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    'coxeter',
    'crystals',
    'mendeleev',
    'pymatgen',
    'numpy',
    'scipy',
    'pyyaml',
    'matplotlib',
    'setuptools_scm'
]



dynamic = ["version"]

# [project.optional-dependencies]
# pdf = ["ReportLab>=1.2", "RXP"]
# rest = ["docutils>=0.3", "pack==1.1", "pack==1.3"]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/lllangWV/MatGraphDB"
Issues = "https://github.com/lllangWV/MatGraphDB/issues"
Changelog = "https://github.com/lllangWV/MatGraphDB/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["matgraphdb*"]
exclude = ["matgraphdb.tests*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
version_file = "pkg/_version.py"
